name = input("Enter your name: ")
city = input("Enter your city: ")
fav_food = input("Enter ur fav food: ")
fav_movie = input("Enter ur fav movie: ")
hobbies = input("Enter ur hobbies: ")
fav_actor = input("Enter ur fav actor: ")
fav_actress = input("Enter ur fav actress: ")
fav_author = input("Enter ur fav author: ")
fav_sports = input("Enter ur fav sports: ")
fav_sportsman = input("Enter ur fav sportsman: ")
fav_dog = input("fav dog breed: ")
fav_singer = input("fav singer: " )

print("!!!!!INFO!!!!!")
print(f'{name=}')
print(f'{city=}')
print(f'{fav_food=}')
print(f'{fav_movie=}')
print(f'{hobbies=}')
print(f'{fav_actor=}')
print(f'{fav_actress=}')
print(f'{fav_author=}')
print(f'{fav_sports=}')
print(f'{fav_sportsman=}')
print(f'{fav_dog=}')
print(f'{fav_singer=}')
